Add All and Every function
thecasualcoder/godash pull request #15
Opened 2019-10-14 03:17 UTC by pearl2201

## Checklist for PR

[] Link to corresponding Issue.
[] Tests covering all the code branches.
[] Validations for all the argument's type. This includes the functions passed as arguments.
[] A Comment on how the function works and what are the different validations in the function.
[] An ExampleTest of the function.
[] README.md should be updated about the function.

2019-10-21 13:58 UTC, dineshba commented on all.go
> +		return output, fmt.Errorf("predicateFn has to be a function")
During error, i think it is better to return false

2019-10-21 14:03 UTC, dineshba requested changes

2019-10-21 14:03 UTC, dineshba commented on README.md
> +	var output []int
output is of type `bool`

2019-10-21 14:03 UTC, dineshba commented on all.go
> +		return output, nil
we may not need `output` variable at all. We can directly `return false, nil` at line 52 and `return true, nil` at line 57. What do you think @pearl2201 ?

2019-10-21 14:31 UTC, pearl2201 commented
I just commit the change.

2019-10-21 15:11 UTC, dineshba commented on README.md
> +	var output []int
can you make it plain bool `not []bool`

2019-10-21 15:13 UTC, dineshba requested changes

2019-10-21 15:13 UTC, dineshba commented on README.md
> +	var output []bool
should be just bool `not []bool`

2019-10-23 03:58 UTC, dineshba approved these changes

2019-10-23 03:59 UTC, merged